config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "images#index"
  resources :images do
    resource :comments, only:[:create]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :image
  belongs_to :user
end

app/models/image.rb
class Image < ApplicationRecord
  validates :image, presence: true
  attachment :image
  has_many :comments, dependent: :destroy
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, uniqueness: true
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable
  has_many :comments, dependent: :destroy      
  has_many :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    image = Image.find(params[:image_id])
    comment = current_user.comments.new(comment_params)
    comment.image_id = image.id
    comment.save
    redirect_to :images
  end
  private
  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def new
    @image = Image.new
  end
  def create
      @image = Image.new(image_params)
      @image.user_id = current_user.id
      @image.save
      redirect_to :images
  end
  def index
    @images = Image.all.reverse_order
  end
  def show
  end
  def edit
  end
  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    flash[:success] = "delete picture"
    redirect_to :images
  end
  private
  def image_params
    params.require(:image).permit(:title, :image, :caption)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/edit.html.erb
<h1>Images#edit</h1>
<p>Find me in app/views/images/edit.html.erb</p>

app/views/images/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">

      <p class="post-icon">
        <%= link_to new_image_path do %>
        <span class="glyphicon glyphicon-camera" aria-hidden="true"></span>
        <% end %>
      </p>
    </div>
    <div class="col-xs-6">
      <h3 class="delete-flash"><%= flash[:success] %></h3><br>
      <h1 class="index-title">Picture index</h1>


      <% if Image.blank? %>
        <h3>No Picture</h3>
      <% end %>
      <% @images.each do |image| %>
      <div class="post-image-box">
        <p class="user-name"><%= link_to image.user.name, "#" %></p>
        <div class="post-image">
          <%= attachment_image_tag image, :image, :fill, 500, 300 %><br>
        </div>
        <div class="icon-box">
          <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
          <span class="glyphicon glyphicon-comment" aria-hidden="true"></span>
          <span class="glyphicon glyphicon-paperclip" aria-hidden="true"></span>
        </div>
        <div class="delete-icon">
          <% if image.user_id == current_user.id %>
            <%= link_to image, method: :delete do %>
            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
            <% end %>
          <% end %>
        </div>
        <div class="image-text">
            <p　class="user-link"><%= link_to image.user.name, "#" %>
            <%= image.caption %></p>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/images/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <h1>NEW PICTURE</h1>
      <%= form_for(@image) do |f| %>
      <%= f.attachment_field :image %>
      <h3>CAPTION</h3>
      <%= f.text_area :caption %><br>
      <%= f.submit 'POST', class:"btn btn-info" %>
      <% end %>

    </div>
  </div>
</div>

app/views/images/show.html.erb
<h1>Images#show</h1>
<p>Find me in app/views/images/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Picpost</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="nav navbar-default">
        <%= link_to :images do %>
        <p class="home"><span class="glyphicon glyphicon-home" aria-hidden="true"></span></p>
        <% end %><br>
        <% if user_signed_in? %>
        <h3>ログイン中</h3>
        <%= link_to "ログアウト", :destroy_user_session, method: :delete %>
        <% else %>
        <h3>未ログイン</h3>
        <%= link_to "サインアップ", :new_user_registration %>
        <%= link_to "ログイン", :user_session %>
        <% end %>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>